### ISSUE TITLE
How i can use Fever to send event to postgresql DB ?

### ISSUE THREAD

**Issue by hpkit** [DCSO/fever#21]
i run fever with command:
```
fever run -v -db-enable --db-host 10.0.0.189:5432 --db-database events --db-user postgres --db-password postgres
```

postgresql 9.6 on centos 7.3
DB is created via SQL:
```sql
CREATE UNLOGGED TABLE IF NOT EXISTS "events-YY-MM-DD-HHMM"
  (ts timestamp without time zone default now(),
   payload jsonb);
GRANT ALL PRIVILEGES ON TABLE "events-YY-MM-DD-HHMM" to postgres;
```

After first run of fever i run SQL:
```sql
CREATE INDEX ON "events-YY-MM-DD-HHMM" (ts);
CREATE INDEX ON "events-YY-MM-DD-HHMM" (((payload->>'src_ip')::INET), ((payload->>'src_port')::INT));
CREATE INDEX ON "events-YY-MM-DD-HHMM" (((payload->>'dest_ip')::INET), ((payload->>'dest_port')::INT));
CREATE INDEX ON "events-YY-MM-DD-HHMM" ((payload->>'event_type'));
CREATE INDEX ON "events-YY-MM-DD-HHMM" using GIN (trigram_string(payload) gin_trgm_ops)
```

Just now in public scheme i can see:
1 table events-YY-MM-DD-HHMM
15 functions
13 indexes

I send to suricata test events and i can see this  events in fast.log

But in table events-YY-MM-DD-HHMM i cant see any data.

**Comment by satta** [comment]
The tables are automatically generated, with `YY-MM-DD-HHMM` just being a placeholder for the time that a table was rotated. By default, we get one table per hour to limit the overall size. That is, you might get the following tables after running for several hours:
```
events-2019-01-14-1122
events-2019-01-14-1222
events-2019-01-14-1322
...
```
for each hour of each day. So you do not need to create the tables by yourself, nor do you need to create the indexes -- FEVER will automatically start deferred index creation in the background once a table has been rotated. 

Since tables are generated dynamically, all you need to do is make sure that the `postgres` user can `CREATE` and `DROP` tables in the public schema of the `events` database. Do you see anything interesting in the logs for FEVER or PostgreSQL?

**Comment by hpkit** [comment]
postgres user is OWNER of events DB. Via GUI i can create and DROP tables. In Posgresql log i see some SQL Code executed when i run Fever and no more records after...

**Comment by satta** [comment]
And you can't see any new table being created with the name schema I mentioned above? How many test records did you send BTW? By default FEVER collects 50k events before it sends a batch to the database. You can adjust this value (`-c` or `--chunksize`) and set it to a lower value to test under less high load conditions.

**Comment by hpkit** [comment]
Thank you. Its work. I change -c to 1 and events was copyed to DB.
 And another one question:
How i can disable forward options ?

**Comment by satta** [comment]
You can set `-o` or `--out-socket` to the empty string:
```
-o ''
```
to disable forwarding.

**Comment by hpkit** [comment]
Hello, can you help with "alert" events ?  Fever not send it to database.


>Понедельник, 14 января 2019, 17:58 +03:00 от Sascha Steinbiss <notifications@github.com>:
>
>You can set -o or --out-socket to the empty string:
>-o ''
>
>to disable forwarding.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
С уважением,
Сергей Анатольевич

**Comment by satta** [comment]
I will take a look at it later. We've been focusing on live processing/forwarding recently so the database functionality might not have gotten our full attention.
