### ISSUE TITLE
Alert events not sending to Postgresql.

### ISSUE THREAD

**Issue by hpkit** [DCSO/fever#23]
I check regular file of eve-json log and it has a record with type "Alert", but in database sending only events with types "flow,http,dns,stats".

I run fever with command:
```
fever run -v -db-enable --db-host 10.0.0.189:5432 --db-database events --db-user postgres --db-password postgres -c 2 -v -o '' 
```

**Comment by satta** [comment]
At the moment, as soon as a handler is defined for an event type, it is no longer written to the local database, as we used the database more like a dump for everything that wasn't looked at otherwise (but alerts definitely were :)) . I will work on a mechanism to make these configurable independently.
